
logging.level.org.springframework: INFO
logging.level.org.hibernate: ERROR
logging.level.com.zachcalvert: DEBUG

output.templates:
  - name: photos
    types:
      - JPEG
      - JPG
      - TIFF
      - GIF
      - BMP
      - PNG
      - CR2
      - gif
    format:
      - "${base}/photos/${yyyy}/${MM}/${parent_dir}/${filename}"
      - "${base}/photos/${yyyy}/${MM}/${dd}/${filename}"
  - name: movies
    types:
      - avi
      - mov
      - wmv
      - mp4
      - mv4p
      - mpg
      - mpeg
      - m4v
    format:
      - "${base}/movies/${yyyy}/${MM}/${parent_dir}/${filename}"
      - "${base}/movies/${yyyy}/${MM}/${dd}/${filename}"

load:
  ignore:
    - txt
    - pdf
    - mdf
    - sh
    - ini
    - html
    - htm
    - dat
    - db
    - lnk
    - mds
    - mix
    - iso
    - bup
    - ifo
    - vob
    - zip
